### PR TITLE
Correct Header objects

### PR DESCRIPTION
**Pull request by hathawsh**
This PR removes the "name" and "in" fields from Header objects. The OpenAPI spec says they must not be present:

https://spec.openapis.org/oas/latest.html#header-object

Also made two fields optional that were causing validation failures: `allowReserved` and `allowEmptyValue`.

### CODE REVIEW

**Comment by hathawsh** [comment]
Hey @mike-oakley , what are your thoughts on this PR?

**Comment by mike-oakley** [comment]
Sorry - missed this one before!

> This PR removes the "name" and "in" fields from Header objects.
Makes sense - I guess this is breaking but simple transition is to switch to 'Parameter' objects if using 'Header' in the request specs instead of the shared models.

> Also made two fields optional that were causing validation failures: allowReserved and allowEmptyValue.
Can you highlight why this is necessary? Seems that by making them optional we're deviating from the defaults in the OpenAPI spec?

**Comment by mike-oakley** [comment]
👍🏼 sounds good to me

**Comment by manycoding** [comment]
Any updates on this one? This became a blocking issue because of allowEmptyValue

**Comment by hathawsh** [comment]
@manycoding: I learned that if I add `exclude_defaults=True` to the `model_dump` call, the `allowEmptyValue` issue goes away. The generated JSON no longer contains the invalid key.

**Comment by hathawsh** [comment]
@mike-oakley This PR now adds the `openapi-spec-validator` dependency and adds tests that verify we're generating spec-compliant JSON. I added some cases that previously failed validation, particularly a header spec.

**Review by mike-oakley — APPROVED** [review]

**Comment by mike-oakley** [comment]
LGTM - thanks @hathawsh!

**Comment by mike-oakley** [comment]
Released to PyPI in version 0.4.0 🎉

**Pull request merged**
